\" lambda-term-actions.1
\" ---------------------
\" Copyright : (c) 2011, Jeremie Dimino <jeremie@dimino.org>
\" Licence   : BSD3
\"
\" This file is a part of Lambda-Term.

.TH LAMBDA-TERM-ACTIONS 1 "August 2011"

.SH NAME
lambda-term-actions \- Display lambda-term editing actions

.SH SYNOPSIS
.B lambda-term-actions

.SH DESCRIPTION

.B lambda-term-actions
displays the list of actions that can be used in the
~/.config/lambda-term-inputrc file.

.SH AUTHOR
Jérémie Dimino <jeremie@dimino.org>

.SH "SEE ALSO"
.BR lambda-term-inputrc (5).
